server {
    listen 80;

    # Raiz dos arquivos estáticos do React (build)
    root /usr/share/nginx/html;
    index index.html;

    # SPA: redireciona sempre para o index.html (React Router cuida do restante)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
