server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Se a requisição vier para /sigp/..., procura nos arquivos reais
    location /sigp/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /sigp/index.html;
    }

    # Fallback genérico caso a URL chegue sem /sigp/ (ex: proxy pass retirou o prefixo)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
